racine_gestion_candidats:
    resource: "@racineGestionCandidatsBundle/Resources/config/routing.yml"
    prefix:   /

racine_gestion_tests:
    resource: "@racineGestionTestsBundle/Resources/config/routing.yml"
    prefix:   /

racine_gestion_utilisateur:
    resource: "@racineGestionUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /
    

GestionTests:
  resource: "@racineGestionTestsBundle/Controller"
  prefix: /


GestionCandidat:
  resource: "@racineGestionCandidatsBundle/Controller"
  prefix: /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
