jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        racine\GestionUtilisateurBundle\Entity\Utilisateur: 
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
        

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
       
        Utilisateurs:
          entity: {class : racineGestionUtilisateurBundle:Utilisateur,property: username}

    firewalls:
       
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/Admin/login$
            security: false
            
             
      #  main: 
      #      form_login: 
      #        check_path: /Admin/login_check
       #       login_path: /Admin/login
       #       remember_me: true
        #      
        #    remember_me: 
         #       key :      %secret%
         #       lifetime : 60
         #       domain :   ~
         #       path : /
         #       name : "rmbrm"
         #   logout: true
            

        secured_area:
            pattern:    ^/Admin
            form_login:
                check_path: /Admin/login_check
                login_path: /Admin/login
                remember_me: true
                default_target_path: /Admin/Utilisateur
                
 
            remember_me: 
                key :      %secret%
                lifetime : 60
                domain :   ~
                path : /
                name : "rmbrm"
            
            logout: true
            
            logout:
                path:   /Admin/logout
                target: /Admin/login
                invalidate_session: true
                delete_cookies:
                    rmbrm: { path: /, domain: ~ }
   
          
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
         #- { path: ^/Admin, roles: ROLE_SUPER_ADMIN, requires_channel: http}
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
