jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
        Utilisateurs:
            class: racine\GestionUtilisateurBundle\Entity\Utilisateur
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
       
        Candidats :
            class: racine\GestionCandidatsBundle\Entity\Candidat
            algorithm: plaintext
          

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        Utilisateurs:
          entity: {class : racineGestionUtilisateurBundle:Utilisateur,property: username}
        Candidats:
          entity: {class : racineGestionCandidatsBundle:Candidat,property: codesession}
          
        

    firewalls:
       
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_Admin:
            pattern:  ^/Admin/login$
            security: false

        login_Candidat:
            pattern:  ^/Candidat/login$
            security: false
       
        inscription_candidat:
            pattern: ^/Candidat/inscription
            security: false
            
        
        # secured area for Admin
        secured_area_Utilisateurs:      
             
            pattern:    ^/Admin
            provider: Utilisateurs
            form_login:
                check_path: /Admin/login_check
                login_path: /Admin/login
                remember_me: true
                default_target_path: /Admin/Utilisateur

            remember_me: 
                key :      %secret%
                lifetime : 60
                domain :   ~
                path : /
                name : "rmbrm"
            
            logout: true
            
            logout:
                path:   /Admin/logout
                target: /Admin/login
                invalidate_session: true
                delete_cookies:
                    rmbrm: { path: /, domain: ~ }
                    
        # secured area for Candidat               
        secured_area_Candidats:         
                 
            pattern: ^/Candidat
            provider : Candidats
            
            form_login:
                login_path: /Candidat/login
                check_path: /Candidat/login_check
                remember_me: false
                default_target_path: /Candidat/espace
                username_parameter: _codesession
                password_parameter: _codesessionpass
                
            logout: true
            
            logout:
                path:   /Candidat/logout
                target: /Candidat/login
         
          
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
         #- { path: ^/Admin, roles: ROLE_SUPER_ADMIN, requires_channel: http}
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
