
# Ajout de l'utilisateur 
racine_gestion_utilisateur_AjouterUtilisateur_page:
    pattern:  /Utilisateur/Ajouter
    defaults: { _controller: racineGestionUtilisateurBundle:Ajouter:Ajouter }
    
# modification de l'utilisateur 
racine_gestion_utilisateur_MofidierUtilisateur_page:
    pattern:  /Utilisateur/Modifier
    defaults: { _controller: racineGestionUtilisateurBundle:Mofidier:Modifier }