

#lister la liste des utilisateurs
Admin_liste_Utilisateur:
    pattern:  /Admin/Utilisateur/
    defaults: { _controller: racineGestionUtilisateurBundle:Utilisateur:Index }

Admin_liste_Roles:
    pattern:  /Admin/Utilisateur/Roles
    defaults: { _controller: racineGestionUtilisateurBundle:Utilisateur:getRoles }
  

Admin_Ajout_Utilisateur:
    pattern:  /Admin/Utilisateur/add
    defaults: { _controller: racineGestionUtilisateurBundle:Utilisateur:Add }

#Gestion Candidat

Admin_liste_Candidats :
    pattern:  /Admin/Candidat/
    defaults: { _controller: racineGestionUtilisateurBundle:Candidat:Index }

Admin_liste_Candidats_nonvalides :
    pattern:  /Admin/Candidat/NV
    defaults: { _controller: racineGestionUtilisateurBundle:Candidat:getInvalid }

Admin_delete_Candidat :
    pattern:  /Admin/Candidat/delete
    defaults: { _controller: racineGestionUtilisateurBundle:Candidat:delete }

#Authentification
login : 
    pattern : /Admin/login
    defaults : { _controller: racineGestionUtilisateurBundle:Authentification:Login }

Admin_logout:
    pattern : /Admin/logout
    defaults : { _controller: racineGestionUtilisateurBundle:Authentification:Logout }
    
_security_check:
    pattern: /Admin/login_check

Admin_modif_Utilisateur:
     pattern : /Admin/Utilisateur/edit
     defaults: { _controller: racineGestionUtilisateurBundle:Utilisateur:Edit }

Admin_delete_Utilisateur:
     pattern : /Admin/Utilisateur/delete
     defaults: { _controller: racineGestionUtilisateurBundle:Utilisateur:Delete }
     