<?php

namespace racine\GestionTestsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function selectQuestions()
    {
       $q = $this->getEntityManager()->createQuery('Select q.id,q.description,t.title,u.username  from    racineGestionTestsBundle:Question q,
                                                                                                          racineGestionUtilisateurBundle:Utilisateur u,
                                                                                                          racineGestionTestsBundle:Theme t
                                                                                         where  q.theme = t.id   and q.utilisateur = u.id' );
       return $q->getResult();
       
    }
    
}
