<?php

namespace racine\GestionTestsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends EntityRepository
{
    public function selectReponseById($id)
    {
        $q = $this->getEntityManager()->createQuery('Select r.id,r.description,r.isCorrect  from    racineGestionTestsBundle:Reponse r
                                                                                          where  r.question = ?1')->setParameter(1, $id);
        return $q->getResult();
    }
}
