<?php

namespace racine\GestionTestsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository
{
      public function selectTests()
    {
       $q = $this->getEntityManager()->createQuery('Select t.id, t.nom, t.duree, t.nbr_questions, t.duree_max_question,t.description,t.isPublished  from racineGestionTestsBundle:Test t' );
       return $q->getResult();
       
    }
    
     public function selectPublished()
    {
       $q = $this->getEntityManager()->createQuery('Select t.id as id  from racineGestionTestsBundle:Test t where t.isPublished = ?1 ' )->setParameter(1, true);
       return $q->getResult();
       
    }
}
