<?php

namespace racine\GestionTestsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends EntityRepository
{
     public function selectThemes()
    {
       $q = $this->getEntityManager()->createQuery('Select t.id, t.title, t.description  from racineGestionTestsBundle:Theme t' );
       return $q->getResult();
       
    }
}
