<?php

namespace racine\GestionUtilisateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    public function selectUsers()
    {
       $q = $this->getEntityManager()->createQuery('Select u.id, u.username, u.nom, u.prenom, u.email,u.tel  from racineGestionUtilisateurBundle:Utilisateur u ' );
       return $q->getResult();
       
    }
    
}
